# This is a basic workflow to help you get started with Actions

name: Build AWWW

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run build script
        run: |
          sudo apt install wget
          bash awww-build.sh

      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v2.0.0
        with:
          # Artifact name
          name: 
            awww.deb
          path: 
          # Content type for the file
          content-type: # optional, default is application/octet-stream
          # secrets.GITHUB_TOKEN
          repo-token: ${{ secrets.RELEASE_TOKEN }}
